// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNsgdFq55mThSL0y-Y17feKXsQcRX4fXk',
    appId: '1:362151643727:android:59ac969420bf39bd98783a',
    messagingSenderId: '362151643727',
    projectId: 'credentity-1dcce',
    storageBucket: 'credentity-1dcce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYGmclLuYVIHogMNIJ6Sm7hHaj_HQwzs',
    appId: '1:362151643727:ios:c3a344f91126aa8298783a',
    messagingSenderId: '362151643727',
    projectId: 'credentity-1dcce',
    storageBucket: 'credentity-1dcce.appspot.com',
    iosClientId: '362151643727-qvhe9bttsi80ijsor87ds6eot8dsm5q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.credentity',
  );
}
